dist: xenial
language: node_js
node_js: "10"

cache: 
  - pip
  - npm

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      cache: pip

    - cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  homebrew:
    update: true
    packages:
      - python

install:
    - pip install -e .[dev]
    - pip install -r requirements.txt
    - yarn

script:
  - make lint
  - make test

after_success:
    - codecov --token d7d0b682-758d-40d2-9df7-a753e4d84e3b

branches:
  only:
  - master

notifications:
  email: false
