language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -e .[dev]
    - pip install -r requirements.txt
      - python2
    - yarn

script:
  - make lint
  - make test

after_success:
    - codecov --token d7d0b682-758d-40d2-9df7-a753e4d84e3b

branches:
  only:
  - master

notifications:
  email: false
